config/routes.rb
Rails.application.routes.draw do
 
  resources :contents
  devise_for :users
 root 'pages#home'

 get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %>
    <%= f.text_field :titolo %>
  </div>

  <div class="field">
    <%= f.label :descrizione %>
    <%= f.text_area :descrizione %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer brown lighten-3">
  <div class="container">
    <div class="row">
      <div class="col l4 s4">
        <h5 class="white-text">CONCTACT</h5>
        <ul>
          <li><a class="grey-text text-darken-3" href="#!">Email: kleosmetic@gmail.com</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Sede: via pontano 58 </a></li>
          <li><a class="grey-text text-darken-3" href="#!">80077 ischia (NA) </a></li>
          <li><a class="grey-text text-darken-3" href="#!">numero 081 90 ....</a></li>
        </ul>
      </div>
      <div class="col l4 s4">
        <h5 class="white-text">INFORMAZIONI</h5>
        <ul>
          <li><a class="grey-text text-darken-3" href="#!">About</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Spedizioni</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Pagamento</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Privacy e cookie policy</a></li>
        </ul>
      </div>
      <div class="col l4 offset-4 s4">
        <h5 class="brown-text">FIND US ON</h5>
        <ul>
          <li><a class="grey-text text-darken-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Instagram</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Pinterest</a></li>
          <li><a class="grey-text text-darken-3" href="#!">Youtube</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Kleosmetic
    <a class="grey-text text-darken-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed"> 

    <nav class="brown lighten-3">
        <div class="container nav-wrapper">
            <%= link_to 'Kleosmetic', root_path, class: "brand-logo" %>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><%= link_to 'About', about_path %><li>

            <% if user_signed_in? %>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %><li>
            <% else %>  
              <li><%= link_to "Log In", new_user_session_path%><li>
              <li><%= link_to "Sign In", new_user_registration_path%><li>
            <% end %>

          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><%= link_to 'About', about_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %><li>
            <% else %>  
              <li><%= link_to "Log In", new_user_session_path%><li>
              <li><%= link_to "Sign In", new_user_registration_path%><li>
            <% end %>
          </ul>
        </div>
    </nav>
</header>     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  
<nav class="white">
    <div class="nav-wrapper">
      <div class="container">
    <div class="row">
      <div class="center">
        <h15 class="grey-text">free shipping on orders over....</h15>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
      </ul>
    </div>
  </nav>



  <title>Kleoshop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>


<%= render "layouts/header" %>


       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


 <main class="container">  
     <%= yield %>
 </main>

 <%= render "layouts/footer" %>
    
</body>


    <script>
      $(".button-collapse").sideNav();
    </script>
</html>

app/views/pages/about.html.erb
<h1>chi siamo</h1>
<p>Siamo bla bla bla</p>

app/views/pages/home.html.erb
<h1>Home</h1>